apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-spot-cluster
  region: ap-southeast-1a

managedNodeGroups:
  - name: spot
    instanceType: m5.large
    spot: true
    desiredCapacity: 3
    ssh:
      publicKeyName: provisioner
