apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-spot-cluster
  region: ap-southeast-1

managedNodeGroups:
  - name: spot
    instanceType: m5.large
    # your K8 node can be anytime taken back by AWS
    spot: true
    desiredCapacity: 3
    # created to practice EBS static provisioning
    availabilityZones:
      - ap-southeast-1a
    ssh:
      publicKeyName: provisioner
